services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
      
  producer:
    build:
      context: ./python
      dockerfile: Dockerfile.python
    volumes:
      - ./data:/app/data
      - ./python:/app/python

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    volumes:
      - ./data:/app/data
      - ./helloworld.java:/app/helloworld.java


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
