services:
  producer:
    build:
      context: ./python
      dockerfile: Dockerfile.python
    network_mode: host
    volumes:
      - ./data:/app/data
      - ./python:/app/python

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    network_mode: host
    volumes:
      - ./data:/app/data
      - ./helloworld.java:/app/helloworld.java