services:
  producer:
    build:
      context: ./python
      dockerfile: Dockerfile.python
    # ports:
    #   - "9092:9092"
    network_mode: host
    volumes:
      - ./data:/app/data
      - ./python:/app/python

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./helloworld.java:/app/helloworld.java